### ISSUE TITLE
Links in posts should open in a new tab.

### ISSUE THREAD

**Issue by wjpvandenheuvel** [auroral-ui/hexo-theme-aurora#64]
Default behaviour for clicking a link in a post should open a new tab instead of loading in current tab.

**Comment by TriDiamond** [comment]
@wjpvandenheuvel  Since this blog is made into a [SPA](https://en.wikipedia.org/wiki/Single-page_application), therefore any links should be acted as an internal link and transfer within the "APP". However if you want the posts to be opened on an external tab, this would consider to be a feature where user set to force this behavior.

**Comment by TriDiamond** [comment]
This is converted to a feature #93
